### ISSUE TITLE
Can't set base path for clips on another disk

### ISSUE THREAD

**Issue by Romalllka** [qvvonk/smart_replays#1]
not sure how you make a report on github, sorry if it is not following some guidelines
After installing script I can't change the base path to another disk. Every time I am trying to do it, this appears in the logs:

[smart_replays.py] [18.11.2024 02:24:18] Updating script...
[smart_replays.py] [18.11.2024 02:24:18] {"obssmartreplayshk1":[],"obssmartreplayshk2":[],"obssmartreplayshk3":[],"base_path":"D:/OBS POGGERS"}
[smart_replays.py] [18.11.2024 02:24:18] Script updated

but right selecting the folder it changes to "C:\\Users\\Romalllka\\Videos"
my default obs recording path is on disk D as well so i don't know what's wrong

here is a video if it adds any clarity of the issue: https://youtu.be/uqZXT0dvdyM

**Comment by qvvonk** [comment]
Hello, @Romalllka !

I apologize for the long reply, I didn't immediately notice the Issue.

Fixed this bug in update 1.0.1.

https://github.com/qvvonk/smart_replays/releases/tag/v1.0.1

**Comment by qvvonk** [comment]
Message here after you check it out, please.

**Comment by Romalllka** [comment]
Works now, thanks
